
["LeatherTweaks Config"]
	#The following settings only take effect after the game is restarted:
	#Should leather cutting with a knife be enabled?(If disabled the knife will still have functionality as a weapon)
	"Leather Cutting Enabled" = true
	#Should the saddle recipe be enabled?
	"Saddle Recipe Enabled" = true
	#Should the smelting/campfire cooking of rotten flesh into hide be enabled?(hide will still be obtainable through fire aspect if disabled)
	"Rotten Flesh Smelting Enabled" = true
	#Multiplier at which rotten flesh smelts in a furnace(by default this is equal to campfire speed(which is 200))
	"Rotten Flesh Furnace Multiplier" = 1.0
	#Multiplier at which rotten flesh cooks on a campfire(by default this is equal to smelting speed(which is 200))
	"Rotten Flesh Campfire Multiplier" = 1.0
	#The following settings will update after a '/reload' command:
	#How many leather should be returned when cutting a leather helmet?(if enabled)
	"Leather Helmet Return" = 3
	#How many leather should be returned when cutting a leather chestplate?(if enabled)
	"Leather Chestplate Return" = 5
	#How many leather should be returned when cutting leather leggings?(if enabled)
	"Leather Leggings Return" = 4
	#How many leather should be returned when cutting leather boots?(if enabled)
	"Leather Boots Return" = 2
	#How many leather should be returned when cutting leather horse armor?(if enabled)
	"Leather Horse Armor Return" = 4
	#How many leather should be returned when cutting a saddle?(if enabled)
	"Saddle Return" = 3
	#How many hide should be returned when cutting a book?(if enabled)
	"Book Return" = 2

