
["Shields+"]
	#In vanilla when you start blocking with a shield, there's a 0.25 seconds (5 ticks) window where you are still not blocking. With this you can change that or remove it.
	#Range: > 0
	"Shield Windup" = 2
	#If true shields will block only a certain amount of damage. If false the vanilla behaviour is used.
	"Shields Block Fixed Damage Amount" = true
	#The minimum damage dealt to the player for the shield to take damage (reduce durability). Vanilla is 3.
	#Range: 0.0 ~ 3.4028234663852886E38
	"Min Shield Hurt Damage" = 0.0
	#Makes shields always disable for 1.6 seconds like Combat Test snapshots.
	"Combat Test shield disabling" = true

